1 — Import Library

In [ ]:
import pandas as pd
import numpy as np
import re
import string

from tqdm import tqdm

2 — Load Dataset

In [ ]:
from google.colab import files

uploaded = files.upload()
df = pd.read_csv("dataset_balanced_C0-C4.csv")
print("Jumlah data:", len(df))
df.head()

Saving dataset_balanced_C0-C4.csv to dataset_balanced_C0-C4.csv
Jumlah data: 3815

,No,Komentar,Label Awal,Label Pakar,Pasal Dominan,Catatan,Unnamed: 6,clean_comment,Kode Label
0,5708.0,Apakah seorang maling anak'y jg akan menjadi m...,Indikasi penghinaan atau kebencian terhadap in...,Ambigu atau konteks tidak cukup,NaN,Pertanyaan umum tanpa target yang jelas.,NaN,apakah seorang maling anak'y jg akan menjadi m...,C4
1,495.0,"​@HanaFanda-wx1cciyaa betul,\nMeni hese ngesah...",Netral atau tidak terindikasi,Konten ofensif,NaN,Tidak terindikasi Pasal 27A maupun Pasal 28 ay...,NaN,"​@hanafanda-wx1cciyaa betul, meni hese ngesahk...",C2
2,1841.0,Omongan nya pak bahlil sering kontradiksi. Lah...,Netral atau tidak terindikasi,Netral atau tidak terindikasi,NaN,NaN,NaN,omongan nya pak bahlil sering kontradiksi. lah...,C0
3,6483.0,Astagfirullah. Katanya Wakil Rakyat tapi kelak...,Indikasi penghinaan atau kebencian terhadap in...,Konten ofensif,NaN,Menuduh wakil rakyat sebagai maling dan zalim.,NaN,astagfirullah. katanya wakil rakyat tapi kelak...,C2
4,2222.0,"Cobalah pampang ke45 poin itu di media sosial,...",Netral atau tidak terindikasi,Ambigu atau konteks tidak cukup,NaN,komentar ini belum menunjukkan unsur yang cuku...,NaN,"cobalah pampang ke45 poin itu di media sosial,...",C4

3 — Struktur Dataset

In [ ]:
print("Kolom dataset:")
print(df.columns.tolist())

print("\nJumlah data:")
print(len(df))

print("\nDistribusi label:")
print(
    df["Kode Label"]
    .value_counts()
    .sort_index()
)

Kolom dataset:
['No', 'Komentar', 'Label Awal', 'Label Pakar', 'Pasal Dominan', 'Catatan', 'Unnamed: 6', 'clean_comment', 'Kode Label']

Jumlah data:
3815

Distribusi label:
Kode Label
C0    763
C1    763
C2    763
C3    763
C4    763
Name: count, dtype: int64

4 — Contoh Komentar Awal

In [ ]:
df[["Komentar","Kode Label"]].sample(10,random_state=42)

                                               Komentar Kode Label
1078  ya betul buk suruh buktikanan mana PKInya........         C2
1957  TUHAN TDK AKAN MEMBERKATI DLM KEBURUKAN APLG K...         C0
2694   @fatcrruise6508   klo pengen jadi pahlawan, p...         C2
2002  UU perampasan aset para koruptor harus segera ...         C0
1213  Iya Bu....di negri ini banyak yg meruksak...co...         C1
1104  Gugat Gribran wapres plonga plongo . Ini naman...         C3
2654  Keliatan dari ruang kerja yang banyak mainan w...         C2
1694  Memberi jalan kepada komunis untuk berkembang ...         C0
721   Parcok saat ini tempat berkumpulnya para mafia...         C2
949          Selamat berjuang...membrantas mafia di KPK         C1

5 — Fungsi Minimal Cleaning

In [ ]:
def minimal_cleaning(text):
    text = str(text)
    # 1. Case folding
    text = text.lower()

    # 2. Hapus URL
    text = re.sub(r"http\S+|www\S+", "", text)

    # 3. Normalisasi whitespace
    text = re.sub(r"\s+", " ", text)
    return text.strip()

6 — Terapkan Minimal Preprocessing

In [ ]:
df["Komentar_preprocessed"] = (
    df["Komentar"]
    .apply(minimal_cleaning))

print("Minimal preprocessing selesai.")

Minimal preprocessing selesai.

7 — Contoh Hasil

In [ ]:
df[["Komentar", "Komentar_preprocessed", "Kode Label" ]].sample(20, random_state=42)

,Komentar,Komentar_preprocessed,Kode Label
1078,ya betul buk suruh buktikanan mana PKInya........,ya betul buk suruh buktikanan mana pkinya........,C2
1957,TUHAN TDK AKAN MEMBERKATI DLM KEBURUKAN APLG K...,tuhan tdk akan memberkati dlm keburukan aplg k...,C0
2694,"@fatcrruise6508 klo pengen jadi pahlawan, p...","@fatcrruise6508 klo pengen jadi pahlawan, pali...",C2
2002,UU perampasan aset para koruptor harus segera ...,uu perampasan aset para koruptor harus segera ...,C0
1213,Iya Bu....di negri ini banyak yg meruksak...co...,iya bu....di negri ini banyak yg meruksak...co...,C1
1104,Gugat Gribran wapres plonga plongo . Ini naman...,gugat gribran wapres plonga plongo . ini naman...,C3
2654,Keliatan dari ruang kerja yang banyak mainan w...,keliatan dari ruang kerja yang banyak mainan w...,C2
1694,Memberi jalan kepada komunis untuk berkembang ...,memberi jalan kepada komunis untuk berkembang ...,C0
721,Parcok saat ini tempat berkumpulnya para mafia...,parcok saat ini tempat berkumpulnya para mafia...,C2
949,Selamat berjuang...membrantas mafia di KPK,selamat berjuang...membrantas mafia di kpk,C1
2465,Suryo memang sengaja membuka aib pdahal itu ga...,suryo memang sengaja membuka aib pdahal itu ga...,C2
2510,Diskusi ini adalah signal bahaya hancurnya sen...,diskusi ini adalah signal bahaya hancurnya sen...,C1
1270,ga mungkin bro wasit udah masuk dalam sistem,ga mungkin bro wasit udah masuk dalam sistem,C4
564,Luar biasa' pak prabowa cedas dan tulus apa ad...,luar biasa' pak prabowa cedas dan tulus apa ad...,C0
298,Sama-sama Maling teriak Maling 🔥🔥🔥,sama-sama maling teriak maling 🔥🔥🔥,C2
736,integritas Ahok itu pasti pilihan partainya PD...,integritas ahok itu pasti pilihan partainya pd...,C2
744,"Bahlil itu pencuri partai, gmna pencuri itu ma...","bahlil itu pencuri partai, gmna pencuri itu ma...",C3
184,betul bgt tuh biar tdk kurang ajar!!!,betul bgt tuh biar tdk kurang ajar!!!,C4
220,"Dulu saya rasa suka sama psi, sekarang lihat ...","dulu saya rasa suka sama psi, sekarang lihat a...",C1
693,Sama saja mendukung penjahat tahun depan ingat...,sama saja mendukung penjahat tahun depan ingat...,C3

8 — Validasi Missing

In [ ]:
print("Missing pada preprocessing:", df["Komentar_preprocessed"].isnull().sum())
print("Komentar kosong:", (df["Komentar_preprocessed"] == "").sum())

Missing pada preprocessing: 0
Komentar kosong: 0

9 — Statistik Dataset

In [ ]:
print("Jumlah data akhir:", len(df))
print("\nDistribusi label:")
print(df["Kode Label"].value_counts().sort_index())

Jumlah data akhir: 3815

Distribusi label:
Kode Label
C0    763
C1    763
C2    763
C3    763
C4    763
Name: count, dtype: int64

10 — Jumlah Kata

In [ ]:
df["jumlah_kata"] = (df["Komentar_preprocessed"].str.split().str.len())
print(df["jumlah_kata"].describe())

count    3815.000000
mean       24.371429
std        37.368854
min         1.000000
25%         8.000000
50%        15.000000
75%        28.000000
max       709.000000
Name: jumlah_kata, dtype: float64

11 — Bandingkan Contoh Informasi yang Dipertahankan

In [ ]:
df[["Komentar", "Komentar_preprocessed", "jumlah_kata", "Kode Label"]].sample(30, random_state=42)

,Komentar,Komentar_preprocessed,jumlah_kata,Kode Label
1078,ya betul buk suruh buktikanan mana PKInya........,ya betul buk suruh buktikanan mana pkinya........,18,C2
1957,TUHAN TDK AKAN MEMBERKATI DLM KEBURUKAN APLG K...,tuhan tdk akan memberkati dlm keburukan aplg k...,11,C0
2694,"@fatcrruise6508 klo pengen jadi pahlawan, p...","@fatcrruise6508 klo pengen jadi pahlawan, pali...",35,C2
2002,UU perampasan aset para koruptor harus segera ...,uu perampasan aset para koruptor harus segera ...,9,C0
1213,Iya Bu....di negri ini banyak yg meruksak...co...,iya bu....di negri ini banyak yg meruksak...co...,15,C1
1104,Gugat Gribran wapres plonga plongo . Ini naman...,gugat gribran wapres plonga plongo . ini naman...,27,C3
2654,Keliatan dari ruang kerja yang banyak mainan w...,keliatan dari ruang kerja yang banyak mainan w...,28,C2
1694,Memberi jalan kepada komunis untuk berkembang ...,memberi jalan kepada komunis untuk berkembang ...,17,C0
721,Parcok saat ini tempat berkumpulnya para mafia...,parcok saat ini tempat berkumpulnya para mafia...,11,C2
949,Selamat berjuang...membrantas mafia di KPK,selamat berjuang...membrantas mafia di kpk,5,C1
2465,Suryo memang sengaja membuka aib pdahal itu ga...,suryo memang sengaja membuka aib pdahal itu ga...,72,C2
2510,Diskusi ini adalah signal bahaya hancurnya sen...,diskusi ini adalah signal bahaya hancurnya sen...,31,C1
1270,ga mungkin bro wasit udah masuk dalam sistem,ga mungkin bro wasit udah masuk dalam sistem,8,C4
564,Luar biasa' pak prabowa cedas dan tulus apa ad...,luar biasa' pak prabowa cedas dan tulus apa ad...,9,C0
298,Sama-sama Maling teriak Maling 🔥🔥🔥,sama-sama maling teriak maling 🔥🔥🔥,5,C2
736,integritas Ahok itu pasti pilihan partainya PD...,integritas ahok itu pasti pilihan partainya pd...,7,C2
744,"Bahlil itu pencuri partai, gmna pencuri itu ma...","bahlil itu pencuri partai, gmna pencuri itu ma...",11,C3
184,betul bgt tuh biar tdk kurang ajar!!!,betul bgt tuh biar tdk kurang ajar!!!,7,C4
220,"Dulu saya rasa suka sama psi, sekarang lihat ...","dulu saya rasa suka sama psi, sekarang lihat a...",10,C1
693,Sama saja mendukung penjahat tahun depan ingat...,sama saja mendukung penjahat tahun depan ingat...,15,C3
3344,Dari dulu... heran kok masih ada ni partai,dari dulu... heran kok masih ada ni partai,8,C1
1866,Hmmmmm,hmmmmm,1,C4
211,Politik Identitas Indah dari mana RH kementeri...,politik identitas indah dari mana rh kementeri...,139,C1
3581,kan emang mulyono yg ngenalin tedi ke wowo,kan emang mulyono yg ngenalin tedi ke wowo,8,C4
149,Nah betul sudah waktunya dia bersantai menikma...,nah betul sudah waktunya dia bersantai menikma...,21,C2
2872,Kenapa firli punya trek rekod yg buruk tpibrez...,kenapa firli punya trek rekod yg buruk tpibrez...,18,C2
393,"Nikmatin aja ok gas "" gas hancur akibat pemilu...","nikmatin aja ok gas "" gas hancur akibat pemilu...",10,C1
2889,Ah pak pigai udah banyak minum susu ni 😂😂😂😂😂😂😂...,ah pak pigai udah banyak minum susu ni 😂😂😂😂😂😂😂...,14,C3
2172,Komunis sudah musnah.. tinggal skrg yg perlu d...,komunis sudah musnah.. tinggal skrg yg perlu d...,10,C3
883,Roy suryo cs dan rakyatnya makin panik,roy suryo cs dan rakyatnya makin panik,7,C4

12 — Cek Duplicate

In [ ]:
jumlah_duplicate = (
    df["Komentar_preprocessed"]
    .duplicated()
    .sum())

print("Jumlah duplicate preprocessing minimal:", jumlah_duplicate)

Jumlah duplicate preprocessing minimal: 1

13 — Tampilkan Duplicate

In [ ]:
df_duplicate = df[
    df["Komentar_preprocessed"]
    .duplicated(keep=False)
].copy()

print("Jumlah baris dalam kelompok duplicate:", len(df_duplicate))
display(df_duplicate[["No", "Komentar", "Komentar_preprocessed", "Kode Label"]])

Jumlah baris dalam kelompok duplicate: 2

,No,Komentar,Komentar_preprocessed,Kode Label
424,4959.0,"Lanjut atas, \nGusDur sendiri saat jadi presid...","lanjut atas, gusdur sendiri saat jadi presiden...",C3
2653,6357.0,"Lanjut atas,\nGusDur sendiri saat jadi preside...","lanjut atas, gusdur sendiri saat jadi presiden...",C3

14 — Distribusi Panjang Komentar

In [ ]:
def kategori_panjang(n):
    if n <= 5:
        return "1–5 kata"
    elif n <= 10:
        return "6–10 kata"
    elif n <= 20:
        return "11–20 kata"
    else:
        return ">20 kata"

df["Kategori_Panjang"] = (
    df["jumlah_kata"]
    .apply(kategori_panjang))

tabel_panjang = pd.crosstab(
    df["Kategori_Panjang"],
    df["Kode Label"])

urutan = [
    "1–5 kata",
    "6–10 kata",
    "11–20 kata",
    ">20 kata"]

tabel_panjang = (
    tabel_panjang
    .reindex(urutan)
    .fillna(0)
    .astype(int))

display(tabel_panjang)

Kode Label         C0   C1   C2   C3   C4
Kategori_Panjang
1–5 kata          122   55   84   36  278
6–10 kata         171  115  177  117  196
11–20 kata        216  226  232  209  199
>20 kata          254  367  270  401   90

15 — Simpan Dataset Minimal

In [ ]:
output_file = ("dataset_minimal_C0-C4.csv")
df.to_csv(output_file, index=False)

print("Dataset berhasil disimpan:", output_file)
files.download("dataset_minimal_C0-C4.csv")

Dataset berhasil disimpan: dataset_minimal_C0-C4.csv