In [ ]:
# ============================================================
# CELL 1 — CLONE / UPDATE GITHUB REPOSITORY
# ============================================================

import os
import subprocess

REPO_DIR = "/content/TA"

if os.path.exists(os.path.join(REPO_DIR, ".git")):
    print("Repository sudah ada.")

    result = subprocess.run(
        ["git", "pull", "origin", "main"],
        cwd=REPO_DIR,
        capture_output=True,
        text=True
    )

    print(result.stdout)
    print(result.stderr)

else:
    result = subprocess.run(
        [
            "git",
            "clone",
            "https://github.com/shefiramarizcha62-sudo/TA.git",
            REPO_DIR
        ],
        capture_output=True,
        text=True
    )

    print(result.stdout)
    print(result.stderr)

print("\nRepository:", REPO_DIR)

Cloning into '/content/TA'...


Repository: /content/TA

In [ ]:

# LOAD DATASET MINIMAL DARI REPOSITORY
# VIEW 1

import os
import pandas as pd

REPO_DIR = "/content/TA"

MINIMAL_PATH = os.path.join(
    REPO_DIR,
    "dataset",
    "dataset_minimal_C0-C4.csv"
)

print("=" * 70)
print("LOAD DATASET MINIMAL")
print("=" * 70)

print("Path:")
print(MINIMAL_PATH)

if not os.path.exists(MINIMAL_PATH):
    raise FileNotFoundError(
        f"Dataset tidak ditemukan:\n{MINIMAL_PATH}"
    )

minimal_df = pd.read_csv(MINIMAL_PATH)

print("\nShape:", minimal_df.shape)

print("\nKolom:")
print(minimal_df.columns.tolist())

print("\n5 data pertama:")
display(minimal_df.head())

======================================================================
LOAD DATASET MINIMAL
======================================================================
Path:
/content/TA/dataset/dataset_minimal_C0-C4.csv

Shape: (3815, 12)

Kolom:
['No', 'Komentar', 'Label Awal', 'Label Pakar', 'Pasal Dominan', 'Catatan', 'Unnamed: 6', 'clean_comment', 'Kode Label', 'Komentar_preprocessed', 'jumlah_kata', 'Kategori_Panjang']

5 data pertama:

,No,Komentar,Label Awal,Label Pakar,Pasal Dominan,Catatan,Unnamed: 6,clean_comment,Kode Label,Komentar_preprocessed,jumlah_kata,Kategori_Panjang
0,5708.0,Apakah seorang maling anak'y jg akan menjadi m...,Indikasi penghinaan atau kebencian terhadap in...,Ambigu atau konteks tidak cukup,NaN,Pertanyaan umum tanpa target yang jelas.,NaN,apakah seorang maling anak'y jg akan menjadi m...,C4,apakah seorang maling anak'y jg akan menjadi m...,8,6–10 kata
1,495.0,"​@HanaFanda-wx1cciyaa betul,\nMeni hese ngesah...",Netral atau tidak terindikasi,Konten ofensif,NaN,Tidak terindikasi Pasal 27A maupun Pasal 28 ay...,NaN,"​@hanafanda-wx1cciyaa betul, meni hese ngesahk...",C2,"​@hanafanda-wx1cciyaa betul, meni hese ngesahk...",12,11–20 kata
2,1841.0,Omongan nya pak bahlil sering kontradiksi. Lah...,Netral atau tidak terindikasi,Netral atau tidak terindikasi,NaN,NaN,NaN,omongan nya pak bahlil sering kontradiksi. lah...,C0,omongan nya pak bahlil sering kontradiksi. lah...,7,6–10 kata
3,6483.0,Astagfirullah. Katanya Wakil Rakyat tapi kelak...,Indikasi penghinaan atau kebencian terhadap in...,Konten ofensif,NaN,Menuduh wakil rakyat sebagai maling dan zalim.,NaN,astagfirullah. katanya wakil rakyat tapi kelak...,C2,astagfirullah. katanya wakil rakyat tapi kelak...,13,11–20 kata
4,2222.0,"Cobalah pampang ke45 poin itu di media sosial,...",Netral atau tidak terindikasi,Ambigu atau konteks tidak cukup,NaN,komentar ini belum menunjukkan unsur yang cuku...,NaN,"cobalah pampang ke45 poin itu di media sosial,...",C4,"cobalah pampang ke45 poin itu di media sosial,...",12,11–20 kata

In [ ]:
TEXT_COL = "Komentar_preprocessed"
LABEL_COL = "Kode Label"

In [ ]:

# SPLIT MINIMAL DATASET
# view 2

from sklearn.model_selection import train_test_split

RANDOM_STATE = 42

print("Label distribution:")
print(
    minimal_df["Kode Label"]
    .value_counts()
    .sort_index()
)

# Train 80%, temporary 20%

train_minimal, temp_minimal = train_test_split(
    minimal_df,
    test_size=0.20,
    stratify=minimal_df["Kode Label"],
    random_state=RANDOM_STATE
)

# Validation 10%, Test 10%


val_minimal, test_minimal = train_test_split(
    temp_minimal,
    test_size=0.50,
    stratify=temp_minimal["Kode Label"],
    random_state=RANDOM_STATE
)

print("=" * 70)
print("NEW MINIMAL DATASET SPLIT")
print("=" * 70)

print("Train      :", train_minimal.shape)
print("Validation :", val_minimal.shape)
print("Test       :", test_minimal.shape)

print("\nTrain:")
print(train_minimal["Kode Label"].value_counts().sort_index())

print("\nValidation:")
print(val_minimal["Kode Label"].value_counts().sort_index())

print("\nTest:")
print(test_minimal["Kode Label"].value_counts().sort_index())

Label distribution:
Kode Label
C0    763
C1    763
C2    763
C3    763
C4    763
Name: count, dtype: int64
======================================================================
NEW MINIMAL DATASET SPLIT
======================================================================
Train      : (3052, 12)
Validation : (381, 12)
Test       : (382, 12)

Train:
Kode Label
C0    610
C1    611
C2    610
C3    610
C4    611
Name: count, dtype: int64

Validation:
Kode Label
C0    76
C1    76
C2    77
C3    76
C4    76
Name: count, dtype: int64

Test:
Kode Label
C0    77
C1    76
C2    76
C3    77
C4    76
Name: count, dtype: int64

In [ ]:
# ============================================================
# SAVE MINIMAL SPLITS INSIDE DATASET FOLDER
# ============================================================

import os

REPO_DIR = "/content/TA"

MINIMAL_SPLIT_DIR = os.path.join(
    REPO_DIR,
    "dataset",
    "split minimal"
)

os.makedirs(
    MINIMAL_SPLIT_DIR,
    exist_ok=True
)

train_minimal.to_csv(
    os.path.join(
        MINIMAL_SPLIT_DIR,
        "train_split_minimal.csv"
    ),
    index=False
)

val_minimal.to_csv(
    os.path.join(
        MINIMAL_SPLIT_DIR,
        "validation_split_minimal.csv"
    ),
    index=False
)

test_minimal.to_csv(
    os.path.join(
        MINIMAL_SPLIT_DIR,
        "test_split_minimal.csv"
    ),
    index=False
)

print("=" * 70)
print("MINIMAL SPLITS SAVED")
print("=" * 70)

print(MINIMAL_SPLIT_DIR)

for file in sorted(os.listdir(MINIMAL_SPLIT_DIR)):
    path = os.path.join(
        MINIMAL_SPLIT_DIR,
        file
    )

    print(
        file,
        "→",
        f"{os.path.getsize(path) / (1024 * 1024):.2f} MB"
    )

======================================================================
MINIMAL SPLITS SAVED
======================================================================
/content/TA/dataset/split minimal
test_split_minimal.csv → 0.26 MB
train_split_minimal.csv → 2.05 MB
validation_split_minimal.csv → 0.27 MB

In [ ]:
# ============================================================
# CELL 1 — LOAD MINIMAL SPLITS
# ============================================================

import os
import pandas as pd

REPO_DIR = "/content/TA"

MINIMAL_SPLIT_DIR = os.path.join(
    REPO_DIR,
    "dataset",
    "split minimal"
)

TRAIN_PATH = os.path.join(
    MINIMAL_SPLIT_DIR,
    "train_split_minimal.csv"
)

VAL_PATH = os.path.join(
    MINIMAL_SPLIT_DIR,
    "validation_split_minimal.csv"
)

TEST_PATH = os.path.join(
    MINIMAL_SPLIT_DIR,
    "test_split_minimal.csv"
)

train_df = pd.read_csv(TRAIN_PATH)
val_df = pd.read_csv(VAL_PATH)
test_df = pd.read_csv(TEST_PATH)

print("=" * 70)
print("MINIMAL PREPROCESSING SPLITS")
print("=" * 70)

print("Train      :", train_df.shape)
print("Validation :", val_df.shape)
print("Test       :", test_df.shape)

print("\nColumns:")
print(train_df.columns.tolist())

======================================================================
MINIMAL PREPROCESSING SPLITS
======================================================================
Train      : (3052, 12)
Validation : (381, 12)
Test       : (382, 12)

Columns:
['No', 'Komentar', 'Label Awal', 'Label Pakar', 'Pasal Dominan', 'Catatan', 'Unnamed: 6', 'clean_comment', 'Kode Label', 'Komentar_preprocessed', 'jumlah_kata', 'Kategori_Panjang']

In [ ]:
# ============================================================
# CELL 2 — CHECK LABEL DISTRIBUTION
# ============================================================

LABEL_COL = "Kode Label"
TEXT_COL = "Komentar_preprocessed"

print("=" * 70)
print("LABEL DISTRIBUTION")
print("=" * 70)

print("\nTrain:")
print(
    train_df[LABEL_COL]
    .value_counts()
    .sort_index()
)

print("\nValidation:")
print(
    val_df[LABEL_COL]
    .value_counts()
    .sort_index()
)

print("\nTest:")
print(
    test_df[LABEL_COL]
    .value_counts()
    .sort_index()
)

======================================================================
LABEL DISTRIBUTION
======================================================================

Train:
Kode Label
C0    610
C1    611
C2    610
C3    610
C4    611
Name: count, dtype: int64

Validation:
Kode Label
C0    76
C1    76
C2    77
C3    76
C4    76
Name: count, dtype: int64

Test:
Kode Label
C0    77
C1    76
C2    76
C3    77
C4    76
Name: count, dtype: int64

In [ ]:
# ============================================================
# CELL 3 — LABEL MAPPING
# ============================================================

label2id = {
    "C0": 0,
    "C1": 1,
    "C2": 2,
    "C3": 3,
    "C4": 4
}

id2label = {
    0: "C0",
    1: "C1",
    2: "C2",
    3: "C3",
    4: "C4"
}

for df in [train_df, val_df, test_df]:
    df["label"] = df[LABEL_COL].map(label2id)

print("Label mapping:")
print(label2id)

print("\nMapped labels:")
print(
    train_df["label"]
    .value_counts()
    .sort_index()
)

Label mapping:
{'C0': 0, 'C1': 1, 'C2': 2, 'C3': 3, 'C4': 4}

Mapped labels:
label
0    610
1    611
2    610
3    610
4    611
Name: count, dtype: int64

In [ ]:
# ============================================================
# CELL 4 — CONVERT TO HUGGING FACE DATASET
# ============================================================

from datasets import Dataset

train_dataset = Dataset.from_pandas(
    train_df[[TEXT_COL, "label"]],
    preserve_index=False
)

val_dataset = Dataset.from_pandas(
    val_df[[TEXT_COL, "label"]],
    preserve_index=False
)

test_dataset = Dataset.from_pandas(
    test_df[[TEXT_COL, "label"]],
    preserve_index=False
)

print("Train:", train_dataset)
print("Val  :", val_dataset)
print("Test :", test_dataset)

Train: Dataset({
    features: ['Komentar_preprocessed', 'label'],
    num_rows: 3052
})
Val  : Dataset({
    features: ['Komentar_preprocessed', 'label'],
    num_rows: 381
})
Test : Dataset({
    features: ['Komentar_preprocessed', 'label'],
    num_rows: 382
})

In [ ]:
# ============================================================
# CELL 5 — TOKENIZER
# ============================================================

from transformers import AutoTokenizer

MODEL_NAME = "indobenchmark/indobert-large-p2"
MODEL_LABEL = "IndoBERT Large P2"

MAX_LENGTH = 256

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

print("=" * 70)
print("TOKENIZER")
print("=" * 70)

print("Model      :", MODEL_LABEL)
print("Tokenizer  :", tokenizer.__class__.__name__)
print("MAX_LENGTH :", MAX_LENGTH)

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

======================================================================
TOKENIZER
======================================================================
Model      : IndoBERT Large P2
Tokenizer  : BertTokenizer
MAX_LENGTH : 256

In [ ]:
# ============================================================
# CELL 6 — TOKENIZATION
# ============================================================

def tokenize_function(examples):
    return tokenizer(
        examples[TEXT_COL],
        truncation=True,
        max_length=MAX_LENGTH
    )

train_tokenized = train_dataset.map(
    tokenize_function,
    batched=True
)

val_tokenized = val_dataset.map(
    tokenize_function,
    batched=True
)

test_tokenized = test_dataset.map(
    tokenize_function,
    batched=True
)

print("Tokenization selesai.")

print("\nTrain columns:")
print(train_tokenized.column_names)

Map:   0%|          | 0/3052 [00:00<?, ? examples/s]

Map:   0%|          | 0/381 [00:00<?, ? examples/s]

Map:   0%|          | 0/382 [00:00<?, ? examples/s]

Tokenization selesai.

Train columns:
['Komentar_preprocessed', 'label', 'input_ids', 'token_type_ids', 'attention_mask']

In [ ]:
# ============================================================
# CELL 7 — LOAD INDOBERT LARGE P2
# ============================================================

import torch
import numpy as np

from transformers import (
    AutoModelForSequenceClassification,
    DataCollatorWithPadding
)

MODEL_NAME = "indobenchmark/indobert-large-p2"
MODEL_LABEL = "IndoBERT Large P2"

MAX_LENGTH = 256

label2id = {
    "C0": 0,
    "C1": 1,
    "C2": 2,
    "C3": 3,
    "C4": 4
}

id2label = {
    0: "C0",
    1: "C1",
    2: "C2",
    3: "C3",
    4: "C4"
}

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=5,
    id2label=id2label,
    label2id=label2id
)

print("=" * 70)
print("MODEL LOADED")
print("=" * 70)

print("Model :", MODEL_LABEL)
print("Labels:", model.num_labels)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 1.34GB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertForSequenceClassification LOAD REPORT from: indobenchmark/indobert-large-p2
Key               | Status  |
------------------+---------+-
classifier.weight | MISSING |
classifier.bias   | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

======================================================================
MODEL LOADED
======================================================================
Model : IndoBERT Large P2
Labels: 5
GPU: Tesla T4

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.34GB

model.safetensors: downloading bytes:           |  0.00B

In [ ]:
# ============================================================
# CELL 10 — METRICS
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support
)

def compute_metrics(eval_pred):

    logits, labels = eval_pred

    predictions = np.argmax(
        logits,
        axis=1
    )

    precision, recall, f1, _ = (
        precision_recall_fscore_support(
            labels,
            predictions,
            average="macro",
            zero_division=0
        )
    )

    accuracy = accuracy_score(
        labels,
        predictions
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1_macro": f1
    }

In [ ]:
# ============================================================
# CELL 11 — DATA COLLATOR
# ============================================================

data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer
)

print("Data collator ready.")

Data collator ready.

In [ ]:

# CELL 12 — TRAINING ARGUMENTS
# view

from transformers import TrainingArguments

OUTPUT_DIR = "/content/minimal_large_p2_model"

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,

    # --------------------------------------------------------
    # Training
    # --------------------------------------------------------

    num_train_epochs=10,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,

    learning_rate=2e-5,
    weight_decay=0.01,

    # --------------------------------------------------------
    # Evaluation & checkpoint
    # --------------------------------------------------------

    eval_strategy="epoch",
    save_strategy="epoch",

    load_best_model_at_end=True,

    metric_for_best_model="f1_macro",
    greater_is_better=True,

    # --------------------------------------------------------
    # Logging
    # --------------------------------------------------------

    logging_strategy="epoch",

    # --------------------------------------------------------
    # Performance
    # --------------------------------------------------------

    fp16=torch.cuda.is_available(),

    # --------------------------------------------------------
    # Reproducibility
    # --------------------------------------------------------

    seed=42,

    # --------------------------------------------------------
    # Disable external logging
    # --------------------------------------------------------

    report_to="none"
)

print("=" * 70)
print("TRAINING CONFIGURATION")
print("=" * 70)

print("Model          :", MODEL_LABEL)
print("MAX_LENGTH     :", MAX_LENGTH)
print("Learning rate  :", 2e-5)
print("Weight decay   :", 0.01)
print("Class weighted : False")
print("Max epochs     :", 10)
print("Early stopping : 2")
print("FP16           :", torch.cuda.is_available())

======================================================================
TRAINING CONFIGURATION
======================================================================
Model          : IndoBERT Large P2
MAX_LENGTH     : 256
Learning rate  : 2e-05
Weight decay   : 0.01
Class weighted : True
Max epochs     : 10
Early stopping : 2
FP16           : True

In [ ]:
# ============================================================
# TRAINER
# ============================================================

from transformers import Trainer, EarlyStoppingCallback

trainer = Trainer(
    model=model,
    args=training_args,

    train_dataset=train_tokenized,
    eval_dataset=val_tokenized,

    processing_class=tokenizer,
    data_collator=data_collator,

    compute_metrics=compute_metrics,

    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=2
        )
    ]
)

print("Trainer ready.")

Trainer ready.

In [ ]:
# ============================================================
# TRAINING
# ============================================================

print("=" * 70)
print("START TRAINING")
print("=" * 70)

train_result = trainer.train()

print("\nTraining selesai.")

======================================================================
START TRAINING
======================================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training selesai.

In [ ]:
# ============================================================
# TEST — BEST MODEL
# ============================================================

test_results = trainer.evaluate(
    eval_dataset=test_tokenized
)

print("=" * 70)
print("TEST RESULT — BEST MODEL")
print("=" * 70)

for key, value in test_results.items():
    if isinstance(value, float):
        print(f"{key:<20}: {value:.6f}")
    else:
        print(f"{key:<20}: {value}")

======================================================================
TEST RESULT — BEST MODEL
======================================================================
eval_loss           : 1.379602
eval_accuracy       : 0.473822
eval_precision      : 0.470694
eval_recall         : 0.473240
eval_f1_macro       : 0.455464

In [ ]:
# ============================================================
# TEST PREDICTIONS
# ============================================================

test_output = trainer.predict(
    test_tokenized
)

predictions = np.argmax(
    test_output.predictions,
    axis=1
)

true_labels = test_output.label_ids

print("=" * 70)
print("TEST PREDICTIONS")
print("=" * 70)

print("Jumlah data test :", len(true_labels))
print("Jumlah prediksi  :", len(predictions))
print("Prediction shape :", test_output.predictions.shape)

======================================================================
TEST PREDICTIONS
======================================================================
Jumlah data test : 382
Jumlah prediksi  : 382
Prediction shape : (382, 5)

In [ ]:
# ============================================================
# VALIDATION EVALUATION
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix
)

# Prediction validation
val_output = trainer.predict(
    val_tokenized
)

val_predictions = np.argmax(
    val_output.predictions,
    axis=1
)

val_true = val_output.label_ids

# Metrics
val_precision, val_recall, val_f1, _ = (
    precision_recall_fscore_support(
        val_true,
        val_predictions,
        average="macro",
        zero_division=0
    )
)

val_accuracy = accuracy_score(
    val_true,
    val_predictions
)

# ------------------------------------------------------------
# Metrics DataFrame
# ------------------------------------------------------------

val_metrics_df = pd.DataFrame([{
    "Model": MODEL_LABEL,
    "Dataset": "Validation",
    "Accuracy": val_accuracy,
    "Precision": val_precision,
    "Recall": val_recall,
    "F1 Macro": val_f1
}])

print("=" * 70)
print("VALIDATION METRICS")
print("=" * 70)

display(val_metrics_df)

# view 4

======================================================================
VALIDATION METRICS
======================================================================

               Model     Dataset  Accuracy  Precision    Recall  F1 Macro
0  IndoBERT Large P2  Validation  0.538058    0.54793  0.538824  0.519419

In [ ]:
# ============================================================
# VALIDATION CLASSIFICATION REPORT
# ============================================================

val_report = classification_report(
    val_true,
    val_predictions,
    labels=[0, 1, 2, 3, 4],
    target_names=[
        "C0", "C1", "C2", "C3", "C4"
    ],
    output_dict=True,
    zero_division=0
)

val_report_df = pd.DataFrame(
    val_report
).transpose()

print("=" * 70)
print("VALIDATION CLASSIFICATION REPORT")
print("=" * 70)

display(val_report_df)

======================================================================
VALIDATION CLASSIFICATION REPORT
======================================================================

              precision    recall  f1-score     support
C0             0.555556  0.394737  0.461538   76.000000
C1             0.540230  0.618421  0.576687   76.000000
C2             0.593750  0.246753  0.348624   77.000000
C3             0.513274  0.763158  0.613757   76.000000
C4             0.536842  0.671053  0.596491   76.000000
accuracy       0.538058  0.538058  0.538058    0.538058
macro avg      0.547930  0.538824  0.519419  381.000000
weighted avg   0.548051  0.538058  0.518971  381.000000

In [ ]:

# VALIDATION CONFUSION MATRIX
# view 5

val_cm = confusion_matrix(
    val_true,
    val_predictions,
    labels=[0, 1, 2, 3, 4]
)

val_cm_df = pd.DataFrame(
    val_cm,
    index=["C0", "C1", "C2", "C3", "C4"],
    columns=["C0", "C1", "C2", "C3", "C4"]
)

print("=" * 70)
print("VALIDATION CONFUSION MATRIX")
print("=" * 70)

display(val_cm_df)

======================================================================
VALIDATION CONFUSION MATRIX
======================================================================

    C0  C1  C2  C3  C4
C0  30  13   5   5  23
C1   4  47   3  16   6
C2   9  10  19  29  10
C3   2  11   0  58   5
C4   9   6   5   5  51

In [ ]:
# ============================================================
# TEST EVALUATION
# ============================================================

test_output = trainer.predict(
    test_tokenized
)

test_predictions = np.argmax(
    test_output.predictions,
    axis=1
)

test_true = test_output.label_ids

# Metrics
test_precision, test_recall, test_f1, _ = (
    precision_recall_fscore_support(
        test_true,
        test_predictions,
        average="macro",
        zero_division=0
    )
)

test_accuracy = accuracy_score(
    test_true,
    test_predictions
)

# ------------------------------------------------------------
# Metrics DataFrame
# ------------------------------------------------------------

test_metrics_df = pd.DataFrame([{
    "Model": MODEL_LABEL,
    "Dataset": "Test",
    "Accuracy": test_accuracy,
    "Precision": test_precision,
    "Recall": test_recall,
    "F1 Macro": test_f1
}])

print("=" * 70)
print("TEST METRICS")
print("=" * 70)

display(test_metrics_df)

# VIEW 6

======================================================================
TEST METRICS
======================================================================

               Model Dataset  Accuracy  Precision   Recall  F1 Macro
0  IndoBERT Large P2    Test  0.473822   0.470694  0.47324  0.455464

In [ ]:
# ============================================================
# TEST CLASSIFICATION REPORT
# ============================================================

test_report = classification_report(
    test_true,
    test_predictions,
    labels=[0, 1, 2, 3, 4],
    target_names=[
        "C0", "C1", "C2", "C3", "C4"
    ],
    output_dict=True,
    zero_division=0
)

test_report_df = pd.DataFrame(
    test_report
).transpose()

print("=" * 70)
print("TEST CLASSIFICATION REPORT")
print("=" * 70)

display(test_report_df)

======================================================================
TEST CLASSIFICATION REPORT
======================================================================

              precision    recall  f1-score     support
C0             0.555556  0.454545  0.500000   77.000000
C1             0.466667  0.552632  0.506024   76.000000
C2             0.393939  0.171053  0.238532   76.000000
C3             0.450820  0.714286  0.552764   77.000000
C4             0.486486  0.473684  0.480000   76.000000
accuracy       0.473822  0.473822  0.473822    0.473822
macro avg      0.470694  0.473240  0.455464  382.000000
weighted avg   0.470864  0.473822  0.455835  382.000000

In [ ]:
# ============================================================
# TEST CONFUSION MATRIX
# ============================================================

test_cm = confusion_matrix(
    test_true,
    test_predictions,
    labels=[0, 1, 2, 3, 4]
)

test_cm_df = pd.DataFrame(
    test_cm,
    index=["C0", "C1", "C2", "C3", "C4"],
    columns=["C0", "C1", "C2", "C3", "C4"]
)

print("=" * 70)
print("TEST CONFUSION MATRIX")
print("=" * 70)

display(test_cm_df)

======================================================================
TEST CONFUSION MATRIX
======================================================================

    C0  C1  C2  C3  C4
C0  35  11   3   9  19
C1   5  42   7  17   5
C2   8  18  13  28   9
C3   2  11   4  55   5
C4  13   8   6  13  36

In [ ]:
# ============================================================
# SAVE ALL MINIMAL PREPROCESSING RESULTS
# ============================================================

import os
import json

RESULTS_DIR = os.path.join(
    REPO_DIR,
    "results",
    "optimization_minimal-preprocessed"
)

os.makedirs(
    RESULTS_DIR,
    exist_ok=True
)

# ============================================================
# 1. METRICS
# ============================================================

final_minimal_metrics = pd.DataFrame([{
    "model": MODEL_LABEL,
    "preprocessing": "minimal",
    "max_length": MAX_LENGTH,
    "learning_rate": 2e-5,
    "weight_decay": 0.01,
    "class_weighted": False,
    "max_epochs": 10,
    "early_stopping_patience": 2,

    "validation_accuracy": val_accuracy,
    "validation_precision": val_precision,
    "validation_recall": val_recall,
    "validation_f1_macro": val_f1,

    "test_accuracy": test_accuracy,
    "test_precision": test_precision,
    "test_recall": test_recall,
    "test_f1_macro": test_f1,

    "best_checkpoint": trainer.state.best_model_checkpoint,
    "best_validation_f1": trainer.state.best_metric
}])

METRICS_PATH = os.path.join(
    RESULTS_DIR,
    "final_minimal_metrics.csv"
)

final_minimal_metrics.to_csv(
    METRICS_PATH,
    index=False
)


# ============================================================
# 2. CLASSIFICATION REPORT
# ============================================================

test_report_df.to_csv(
    os.path.join(
        RESULTS_DIR,
        "final_minimal_classification_report.csv"
    )
)


# ============================================================
# 3. CONFUSION MATRIX
# ============================================================

test_cm_df.to_csv(
    os.path.join(
        RESULTS_DIR,
        "final_minimal_confusion_matrix.csv"
    )
)


# ============================================================
# 4. CONFIGURATION
# ============================================================

config = {
    "model": MODEL_LABEL,
    "model_name": MODEL_NAME,
    "preprocessing": "minimal",

    "text_column": TEXT_COL,
    "label_column": LABEL_COL,

    "max_length": MAX_LENGTH,
    "learning_rate": 2e-5,
    "weight_decay": 0.01,

    "class_weighted": False,
    "label_smoothing": False,

    "max_epochs": 10,
    "early_stopping_patience": 2,

    "best_checkpoint": trainer.state.best_model_checkpoint,
    "best_validation_f1": float(trainer.state.best_metric)
}

CONFIG_PATH = os.path.join(
    RESULTS_DIR,
    "final_minimal_config.json"
)

with open(
    CONFIG_PATH,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        config,
        f,
        indent=4,
        ensure_ascii=False
    )


# ============================================================
# CHECK
# ============================================================

print("=" * 70)
print("RESULTS SAVED")
print("=" * 70)

print("Folder:")
print(RESULTS_DIR)

print("\nFiles:")

for file in sorted(os.listdir(RESULTS_DIR)):
    path = os.path.join(
        RESULTS_DIR,
        file
    )

    size_kb = os.path.getsize(path) / 1024

    print(
        f"{file:<45} {size_kb:.2f} KB"
    )

======================================================================
RESULTS SAVED
======================================================================
Folder:
/content/TA/results/optimization_minimal-preprocessed

Files:
final_minimal_classification_report.csv       0.56 KB
final_minimal_config.json                     0.50 KB
final_minimal_confusion_matrix.csv            0.09 KB
final_minimal_metrics.csv                     0.54 KB

In [ ]:
!find "/content/TA/results/optimization_minimal-preprocessed" -type f -print

/content/TA/results/optimization_minimal-preprocessed/final_minimal_metrics.csv
/content/TA/results/optimization_minimal-preprocessed/final_minimal_classification_report.csv
/content/TA/results/optimization_minimal-preprocessed/final_minimal_confusion_matrix.csv
/content/TA/results/optimization_minimal-preprocessed/final_minimal_config.json

In [ ]:
%cd /content/TA

!git add "results/optimization_minimal-preprocessed/"
!git status

/content/TA
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   results/optimization_minimal-preprocessed/final_minimal_classification_report.csv
	new file:   results/optimization_minimal-preprocessed/final_minimal_config.json
	new file:   results/optimization_minimal-preprocessed/final_minimal_confusion_matrix.csv
	new file:   results/optimization_minimal-preprocessed/final_minimal_metrics.csv

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	dataset/split minimal/

In [ ]:
!git config user.name "Shefira Marizcha"
!git config user.email "shefiramarizcha62@webmail.umm.ac.id"

In [ ]:
!git commit -m "Add minimal preprocessing optimization results"
!git push origin main

[main 65633b4] Add minimal preprocessing optimization results
 4 files changed, 33 insertions(+)
 create mode 100644 results/optimization_minimal-preprocessed/final_minimal_classification_report.csv
 create mode 100644 results/optimization_minimal-preprocessed/final_minimal_config.json
 create mode 100644 results/optimization_minimal-preprocessed/final_minimal_confusion_matrix.csv
 create mode 100644 results/optimization_minimal-preprocessed/final_minimal_metrics.csv
fatal: could not read Username for 'https://github.com': No such device or address

In [ ]:
!git remote -v

origin	https://github.com/shefiramarizcha62-sudo/TA.git (fetch)
origin	https://github.com/shefiramarizcha62-sudo/TA.git (push)

In [ ]:
!git push origin main

fatal: could not read Username for 'https://github.com': No such device or address

In [ ]:
from getpass import getpass

token = getpass("Masukkan GitHub PAT: ")

Masukkan GitHub PAT: ··········

In [ ]:
import subprocess

remote = "https://shefiramarizcha62-sudo:" + token + "@github.com/shefiramarizcha62-sudo/TA.git"

subprocess.run(["git", "push", remote, "main"], check=True)

CompletedProcess(args=['git', 'push', 'https://shefiramarizcha62-sudo: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@github.com/shefiramarizcha62-sudo/TA.git', 'main'], returncode=0)

In [ ]:
del token